---
- hosts: all

  tasks:
  - name: Basic deploy of a service
    community.general.terraform:
      project_path: '{{ project_dir }}'
      state: present
      force_init: true

  - name: Testando
    shell: "echo hello world"