---
- hosts: all

  tasks:
  - name: Clone repositório
    ansible.builtin.git:
      repo: https://github.com/Lucas-Marins/projeto-automacao.git
      dest: /tmp/automation

  - name: Deploy maquina virtual
    community.general.terraform:
      project_path: /tmp/automation/terraform/azure/virtual-machines-linux/basic/
      state: present
      force_init: true