---
- hosts: all

  tasks:
  - name: Example clone of a single branch
    ansible.builtin.git:
      repo: https://github.com/Lucas-Marins/projeto-automacao.git
      dest: /tmp/automation

  - name: Deploy maquina virtual
    community.general.terraform:
      project_path: /tmp/automation/terraform/azure/cosmos-db/basic/
      state: present
      force_init: true