---
- hosts: all

  tasks:
  - name: Instalando o pyhon3, virtualenv
    apt:
      pkg:
      - python3
      - virtualenv

  - name: Instalando dependencias com pip
    pip:
      virtualenv: /home/x1000/tcc/venv
      name:
        - django
        - djangorestframework

  - name: Iniciando o projeto
    shell: '. /home/x1000/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc'

  - name: Alterando o hosts do settings
    lineinfile:
      path: /home/x1000/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
 